config/routes.rb
Rails.application.routes.draw do
  

  #Display for foster dogs
  resources :dogs   
    
  #Display for adoptable dogs
  get 'michigan' => 'dogs#michigan'
  post 'michigan' => 'dogs#michigan'

  get 'donate' => 'dogs#donate'

  #Display adoption info and form partial application
  get 'adoption' => 'dogs#adoption'

  devise_for :users
  
  #For Contact Form pg 
  resources :contacts, only: [:new, :create, :destroy]

  #Remove uploaded attachment on Contact Form pg
  delete 'contacts' => 'contacts#destroy'

  #Display Contact Form acceptance to user
  get 'accept' => 'contacts#accept'

  #Displays Dog's Journey pg
  get 'welcome/show'

  get 'about' => 'welcome#about'

  #Displays About Us pg
  post 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/dog.rb
class Dog < ActiveRecord::Base 

  #Filter status for where dogw will be viewed
  scope :foster, -> { where status: 'Foster' }
  scope :adoptable, -> { where status: 'Adoptable' }
  scope :pending, -> { where status: 'Pending' }
  scope :homed, -> { where status: 'Homed' }
  scope :expired, -> { where status: 'Expired' }

  before_validation :set_breedtype, on: :create
  #before_validation :set_name, on: :create   

  attr_accessor :status_choice, :gender_choice, :age_choice, :breed_choice, :cat_choice, :dog_choice, :human_choice, :energy_choice, :temperament_choice, :image
  
  mount_uploader :image, ImageUploader

  #validates :animal_id, presence: true 
  validates :name, presence: true
  validates :age, presence: true
  validates :status, presence: true
  validates :gender, presence: true
  validates :weight, numericality: { only_integer: true }, presence: true
  validates :breed_type, presence: true 
  validates :breed_one, presence: true
  validates :breed_two, presence: true
  validates :cat_compatible, presence: true
  validates :dog_compatible, presence: true
  validates :human_compatible, presence: true
  validates :energy_level, presence: true
  validates :temperament, presence: true
  validates :fee, numericality: { only_integer: true }, presence: true
  validates :description, presence: true
  #validates :image, presence: true, if file_content_type: { allow: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'], 
             #message: 'Only jpeg, png and gif allowed' }

  private
    #Set default for secondary breed_type if purebred is selected
    def set_breedtype
      if breed_type == "Purebreed" 
        self.breed_two = "Not applicable"    
    end
  
    #Capitalize name
    #def set_name
      #@dog.name = @dog.name.capitalize
    #end
  end

  

 

  STATUS_CHOICE = ['Foster', 'Adoptable']
  GENDER_CHOICE = ['Neutered Male', 'Unaltered Male', 'Spayed Female', 'Unaltered Female']
  AGE_CHOICE = ['2 Months', '3 Months', '4 Months', '5 Months', '6 Months', '7 Months', '8 Months', '9 Months', '10 Months', '11 Months', '1 Year', '2 Years', 
    '3 Years', '4 Years', '5 Years', '6 Years', '7 Years', '8 Years', '9 Years']
  CAT_CHOICE = ['Unknown', 'Good with cats', 'Not good with cats']
  DOG_CHOICE = ['Unknown', 'Good with dogs', 'Good with male dogs only', 'Good with female dogs only', 'Not good with other dogs']
  HUMAN_CHOICE = ['Good with women only', 'Good with men only', 'Good with adults & kids', 'Not good with kids']
  ENERGY_CHOICE = ['Very low', 'Low', 'Average', 'High', 'Very high']
  TEMPERAMENT_CHOICE = ['Very submissive', 'Somewhat submissive', 'Average submissive', 'Somewhat dominant', 'Very dominant']
  
  BREED_CHOICE = 
  [
  'Not Applicable',
  'Affenpinscher', 
  'Afghan Hound ',
  'Airedale Terrier', 
  'Akita', 
  'Alaskan Malamute', 
  'American English Coonhound', 
  'American Eskimo Dog (Miniature)', 
  'American Eskimo Dog (Standard)', 
  'American Eskimo Dog (Toy)', 
  'American Foxhound', 
  'American Hairless Terrier',
  'American Staffordshire Terrier', 
  'American Water Spaniel', 
  'Anatolian Shepherd Dog', 
  'Australian Cattle Dog', 
  'Australian Shepherd', 
  'Australian Terrier', 
  'Basenji', 
  'Basset Hound', 
  'Beagle', 
  'Bearded Collie', 
  'Beauceron', 
  'Bedlington Terrier', 
  'Belgian Malinois', 
  'Belgian Sheepdog', 
  'Belgian Tervuren', 
  'Bergamasco', 
  'Berger Picard', 
  'Bernese Mountain Dog', 
  'Bichon FrisÈ', 
  'Black and Tan Coonhound', 
  'Black Russian Terrier', 
  'Bloodhound', 
  'Bluetick Coonhound', 
  'Boerboel', 
  'Border Collie', 
  'Border Terrier', 
  'Borzoi', 
  'Boston Terrier', 
  'Bouvier des Flandres', 
  'Boxer', 
  'Boykin Spaniel', 
  'Briard', 
  'Brittany', 
  'Brussels Griffon', 
  'Bull Terrier', 
  'Bull Terrier (Miniature)', 
  'Bulldog', 
  'Bullmastiff', 
  'Clumber Spaniel',
  'Cairn Terrier', 
  'Canaan Dog', 
  'Cane Corso', 
  'Cardigan Welsh Corgi', 
  'Cavalier King Charles Spaniel', 
  'Cesky Terrier', 
  'Chesapeake Bay Retriever', 
  'Chihuahua', 
  'Chinese Crested Dog', 
  'Chinese Shar Pei', 
  'Chinook', 
  'Chow Chow', 
  'Cirneco dellEtna', 
  'Clumber Spaniel', 
  'Cocker Spaniel', 
  'Collie', 
  'Coton de Tulear', 
  'Curly-Coated Retriever', 
  'Dachshund', 
  'Dalmatian', 
  'Dandie Dinmont Terrier', 
  'Doberman Pinscher', 
  'Dogue de Bordeaux', 
  'English Cocker Spaniel', 
  'English Foxhound', 
  'English Setter', 
  'English Springer Spaniel', 
  'English Toy Spaniel', 
  'Entlebucher Mountain Dog', 
  'Field Spaniel', 
  'Finnish Lapphund', 
  'Finnish Spitz', 
  'Flat-Coated Retriever', 
  'French Bulldog', 
  'German Pinscher', 
  'German Shepherd Dog', 
  'German Shorthaired Pointer', 
  'German Wirehaired Pointer', 
  'Giant Schnauzer', 
  'Glen of Imaal Terrier', 
  'Golden Retriever', 
  'Gordon Setter', 
  'Great Dane', 
  'Great Pyrenees', 
  'Greater Swiss Mountain Dog', 
  'Greyhound', 
  'Harrier', 
  'Havanese', 
  'Ibizan Hound', 
  'Icelandic Sheepdog', 
  'Irish Red and White Setter', 
  'Irish Setter', 
  'Irish Terrier', 
  'Irish Water Spaniel', 
  'Irish Wolfhound', 
  'Italian Greyhound', 
  'Japanese Chin', 
  'Keeshond', 
  'Kerry Blue Terrier', 
  'Komondor', 
  'Kuvasz', 
  'Labrador Retriever', 
  'Lagotto Romagnolo', 
  'Lakeland Terrier', 
  'Leonberger', 
  'Lhasa Apso', 
  'Lˆwchen', 
  'Miniature Schnauzer',
  'Maltese', 
  'Manchester Terrier', 
  'Mastiff', 
  'Miniature American Shepherd', 
  'Miniature Bull Terrier', 
  'Miniature Pinscher', 
  'Miniature Schnauzer', 
  'Neapolitan Mastiff', 
  'Newfoundland', 
  'Norfolk Terrier', 
  'Norwegian Buhund', 
  'Norwegian Elkhound', 
  'Norwegian Lundehund', 
  'Norwich Terrier', 
  'Nova Scotia Duck-Tolling Retriever', 
  'Old English Sheepdog', 
  'Otterhound', 
  'Papillon', 
  'Parson Russell Terrier', 
  'Pekingese', 
  'Pembroke Welsh Corgi', 
  'Petit Basset Griffon VendÈen', 
  'Pharaoh Hound', 
  'Plott', 
  'Pointer', 
  'Polish Lowland Sheepdog', 
  'Pomeranian', 
  'Poodle',  
  'Portuguese Podengo Pequeno', 
  'Portuguese Water Dog', 
  'Pug', 
  'Puli', 
  'Pyrenean Shepherd', 
  'Rat Terrier', 
  'Redbone Coonhound', 
  'Rhodesian Ridgeback', 
  'Rottweiler', 
  'Russell Terrier', 
  'St. Bernard', 
  'Saluki', 
  'Samoyed', 
  'Schipperke', 
  'Scottish Deerhound', 
  'Scottish Terrier', 
  'Sealyham Terrier', 
  'Shetland Sheepdog', 
  'Shiba Inu', 
  'Shih Tzu', 
  'Siberian Husky', 
  'Silky Terrier', 
  'Skye Terrier', 
  'Sloughi', 
  'Smooth Fox Terrier', 
  'Soft-Coated Wheaten Terrier', 
  'Spanish Water Dog', 
  'Staffordshire Bull Terrier', 
  'Standard Schnauzer', 
  'Sussex Spaniel', 
  'Swedish Vallhund', 
  'Tibetan Mastiff', 
  'Tibetan Spaniel', 
  'Tibetan Terrier', 
  'Toy Fox Terrier', 
  'Treeing Walker Coonhound', 
  'Vizsla', 
  'Weimaraner', 
  'Welsh Springer Spaniel', 
  'Welsh Terrier', 
  'West Highland White Terrier', 
  'Whippet', 
  'Wire Fox Terrier', 
  'Wirehaired Pointing Griffon', 
  'Wirehaired Vizsla', 
  'Xoloitzcuintli', 
  'Yorkshire Terrier'
  ]
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
 
  #Display only foster dogs on index.html.erb
  def index
    @dogs = Dog.foster
  end

  def show
  	@dog = Dog.find(params[:id])
  end

  def new
  	@dog = Dog.new
  end

  def edit
  	@dog = Dog.find(params[:id])
  end

  def create
  	@dog = Dog.new(dog_params)
    if @dog.save
      flash[:notice] = "Dog was saved successfully."
      redirect_to @dog
    else
      flash[:error] = "Error: #{@dog.errors.full_messages}."
      render :new 
    end 
  end

  #Display dogs on michigan.html.erb
  def michigan
    @dogs = Dog.adoptable
  end

  def update
    @dog = Dog.find(params[:id])  
    if @dog.update_attributes(dog_params)
       flash[:notice] = "Update successful."
       redirect_to @dog
    else
      flash[:error] = "Error saving input. Please try again."
      render :edit
    end
  end

  def destroy
  	@dog = Dog.find(dog_params[:id])
  	@dog.destroy
    flash[:notice] = "Dog has been removed."
    redirect_to @dog
  end


  private
  def dog_params
  params.require(:dog).permit(:animal_id, :name, :status, :gender, :weight, :age, :breed_type, :breed_one, :breed_two,
         :cat_compatible, :dog_compatible, :human_compatible, :energy_level, :temperament, :fee, :description, :image)
  end
end

app/helpers/dogs_helper.rb
module DogsHelper

  
end

app/views/dogs/_form.html.erb
<!-- Used for entering all data for a new dog -->
<!-- Styling supported by dogs.scss -->

<div class="col-md-6 col-md-offset-3">
  <h1 id="adoptable-title">Add A New Dog</h1>
  
    <!-- Setup client side validation, inform user of missing data upon entry -->
    <%= simple_form_for @dog, validate: true, html: { multipart: true } do |f| %>
      <%= f.input :animal_id, label: 'Animal ID' %>
      <%= f.input :name %>
      <%= f.input :status, collection: Dog::STATUS_CHOICE, label: 'Status' %>
      <%= f.input :gender, collection: Dog::GENDER_CHOICE, label: 'Gender' %>
      <%= f.input :weight, as: :integer %> 
      <%= f.input :age, collection: Dog::AGE_CHOICE, label: 'Age' %> 
      <%= f.input :breed_type, as: :radio_buttons, collection: ['Purebreed', 'Blend'] %>
      <%= f.input :breed_one, collection: Dog::BREED_CHOICE, label: 'Breed One' %> 
      <%= f.input :breed_two, collection: Dog::BREED_CHOICE, label: 'Breed Two' %>          
      <%= f.input :cat_compatible, collection: Dog::CAT_CHOICE, label: 'Cat Compatibility' %> 
      <%= f.input :dog_compatible, collection: Dog::DOG_CHOICE, label: 'Dog Compatibility' %>
      <%= f.input :human_compatible, collection: Dog::HUMAN_CHOICE, label: 'Human Compatibility' %>
      <%= f.input :energy_level, collection: Dog::ENERGY_CHOICE, label: 'Energy Level' %> 
      <%= f.input :temperament, collection: Dog::TEMPERAMENT_CHOICE, label: 'Temperament' %> 
      <%= f.input :fee, as: :integer  %>
      <%= f.text_area :description, label: 'Description', rows: 8,  placeholder: 'Add additional info.' %>
      <%= f.file_field :image %>
      <%= f.submit :submit, class: 'btn btn-success center-block' %>
    <% end %>
</div><!-- ./col-md-6 col-md-offset-3 -->

app/views/dogs/adoption.html.erb
<!-- Styling supported by dogs.scss -->
<!-- Adopton Process description -->

<div class="container-fluid">  
  <div class="row space">
    <div class="col-md-4">
      <span class="glyphicon glyphicon-heart heart"></span>
    </div>
    <div class="col-md-8 feature-right">
    <h3>Our Adoption Process</h3>
      <p>The rescue will not deviate nor make exceptions from this adoption process. This ensures that we pair dogs that are compatible with your family's lifestyle and household environment. We do not use the first-come, first-serve method in selecting potential adopters. We only do private, in-home adoptions around the Detroit area. We do not ship dogs to other states.</p> 
      <p>Our adoption process consists of the following steps.</p>
        <ol>
  	      <li>Adoption application</li>
  	      <li>Phone interview</li>
  	      <li>Meet-and-greet</li>
  	      <li>Reference checks</li>
  	      <li>Home visit</li>
  	      <li>Adoption agreement</li>
        </ol>
        <p>All of our dogs have received the following.</p>
  	      <ul>
  	        <li>Spay/neuter surgery</li>
  	        <li>Full vaccinations</li>
  	        <li>Heartworm test (treated if positive, on preventatives if negative)</li>
            <li>Flea preventative</li>
  	        <li>Microchip</li>
  	      </ul>
  	    <p>The adoption fees vary, and are based on the the age and history of the dog, medical expenses, and transportation costs.</p>
        <p>We are working on an online form, but in the meantime you are welcome to download or print a PDF version. If you are using an Android phone, you will need to install Adobe Acrobat Reader or Word</p>
        <p>If you are ready to fill-out an application, please click the button. You will need to create a username and password. You will also be able to save the form and finish completing it at a later time.</p> 
        <p><span class><%= link_to "Contact Us", new_contact_path %></span> if you have questions, or would like more information about our dogs. 
        <%= button_to "Application", about_path, class: 'btn btn-default center-block' %>
      </p>
    </div><!-- ./col-md-8 feature-right -->
  </div><!-- ./row space -->
</div><!-- ./container -->

app/views/dogs/donate.html.erb
<!-- Styling supported by dogs.scss -->

<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12">
      <h2 class="headers">Ways To Help</h2>
      <hr>
    </div>
  </div>
  <div class="row space">
    <div class="col-md-8 feature-left">
    <h3 class="headers">Adoption Events</h3>
      <p>Volunteers are needed to assist the foster parents and their dogs with setting up crates, walking and playing with dogs, and of course cleanup. Dress comfortably, bring a folding chair, and be prepared to have some fun. If you are at least 18 years old, and have an hour or more to spare, we would love to have you.</p> 
      <p>Please contact Beaches directly for more information. You can also like their Facebook page if you have any questions. Volunteers for the Compass Adoption Events are provided by Beaches.</p>   
    </div>
    <div class="col-md-4">
      <div class="special">
      <p>placeholder</p>
      <p>Beaches Pet Resort and Training Center</br> 
         29335 Harper Ave</br>
         St. Clair Shores, MI 48081</br>
      </p>
      <p><%= link_to image_tag("FB-FindUsonFacebook-online-114.png", class: "img-responsive center-block"), "https://www.facebook.com/Beaches-Pet-Resort-Training-Center-459928417482107/", alt: "Facebook link", target: "_blank" %>
      </p>
      </div><!-- special --> 
    </div><!-- ./col-md-4 -->
  </div><!-- ./row space -->

  <div class="row space">
    <div class="col-md-8 feature-left">
    <h3 class="headers">Donations</h3>
      <p>We are in need of the following items for our rescue. Donations can be dropped off at our adoption events, or arrangements can be made for another time. However, please contact Compass Dog Rescue in advance for scheduling.</p>
      <ul>
        <li>Dog and puppy food</li>
        <li>Collars and leashes (all sizes)</li>
        <li>Dog snacks</li>
        <li>Towels, sheets, blankets, dog beds (new and used)</li>
        <li>Paper towels, cleaning supplies</li>
        <li>Dog coats and jackets (new and used)</li>
        <li>Dog crates (new or used)</li>
      </ul>
      <p>You can also visit our <%= link_to "Amazon Wish List", "https://www.amazon.com/gp/registry/wishlist/36EKRNR2SQGCA/ref=cm_sw_su_w", alt: "Amazon Link", target: "_blank" %> page to view a list of needed items and make a purchase.</p>
     </div><!-- ./col-md-8 feature-left -->
     <div class="col-md-4">
       <p>We also welcome monetary donations. You can mail a check or donate via PayPal.</p>
       <p class="special">Compass Dog Rescue</br> 
         123 Street</br>
         City, MI 12345</br>
      </p>
          <h3 class="special">Donate via PayPal</h3>
          <%= render 'shared/paypal' %>
      </div><!-- ./col-md-4 -->
  </div><!-- ./row space -->

  <div class="row space">
    <div class="col-md-8 feature-left">
    <h3 class="headers">Volunteer</h3>
    <p>There are many ways you can help our rescue. Below are some of the areas we need assistance, but we are open to all ideas. You can always contact us with your suggestions.</p>
    <p>If you are interested in fostering in Texas or Michigan, please fill out an application. Foster parents are provided with crates, food, heartworm and flea preventative. We even cover the costs of medical expenses. You can also volunteer to transport dogs to their doctor's appointments or to another foster.</p>
    <ul>
      <li>Fostering</li>
      <li>Fundraising</li>
      <li>Grant writing</li>
      <li>Dog training</li>
      <li>Dog walking</li>
      <li>Transport dogs to adoption events, doctor's appointments, etc</li>
      <li>Sharing our information on social media</li>
    </ul>
  </div>
  <div class="col-md-4">
      <p>placeholder</p>
    </div><!-- ./col-md-4 -->
  </div><!-- ./row space -->
</div><!-- ./container -->
        

         

app/views/dogs/edit.html.erb
<!-- Used for editing dog information -->
<!-- Styling supported by dogs.scss -->

<div class="container-fluid">
  <div class="col-md-6 col-md-offset-3">
  <h1 id="adoptable-title">Edit A Dog</h1>

  <!-- Search by name or id number -->
  
    <%= simple_form_for @dog, validate: true, html: { multipart: true } do |f| %>
      <%= f.input :animal_id, label: 'Animal ID' %>
      <%= f.input :name %>
      <%= f.input :status, collection: Dog::STATUS_CHOICE, label: 'Status' %>
      <%= f.input :gender, as: :radio_buttons, collection: ['Male', 'Female']  %>
      <%= f.input :weight, as: :integer %> 
      <%= f.input :age, collection: Dog::AGE_CHOICE, label: 'Age' %> 
      <%= f.input :breed_type, as: :radio_buttons, collection: ['Purebreed', 'Blend']  %>
      <%= f.input :breed_one, collection: Dog::BREED_CHOICE, label: 'Breed One' %> 
      <%= f.input :breed_two, collection: Dog::BREED_CHOICE, label: 'Breed Two' %>          
      <%= f.input :cat_compatible, collection: Dog::CAT_CHOICE, label: 'Cat Compatibility' %> 
      <%= f.input :dog_compatible, collection: Dog::DOG_CHOICE, label: 'Dog Compatibility' %>
      <%= f.input :human_compatible, collection: Dog::HUMAN_CHOICE, label: 'Human Compatibility' %>
      <%= f.input :energy_level, collection: Dog::ENERGY_CHOICE, label: 'Energy Level' %> 
      <%= f.input :temperament, collection: Dog::TEMPERAMENT_CHOICE, label: 'Temperament' %> 
      <%= f.input :fee, as: :integer  %>
      <%= f.text_area :description, label: 'Description', rows: 8,  placeholder: 'Add additional info.' %>
      <%= f.file_field :image %>
      <%= f.submit :submit, class: 'btn btn-success center-block' %>
    <% end %>
  </div><!-- col-md-6 col-md-offset-3 -->
</div>

app/views/dogs/index.html.erb
<!-- Foster Dog page -->
<div class="container">

  <!-- Foster Dogs Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="headers">Foster Dogs</h1>
      <p>Dogs on this page are located in the South Texas area. They will not be available for adoption, until they arrive in Michigan. However, you can begin the screening process early by submitting an application.</p>
    </div>
  </div><!-- /.row -->   

  <!-- 3 columns per row -->
  <% @dogs.each_slice(3) do |dogs| %>
    <div class="row space"> 
      <% dogs.each do |dog| %> 
         <div class="col-md-4 adoptable-profile">
          <p><%= image_tag dog.image_url(:thumb), class: "img-responsive img-adoptable center-block" %><p>
          <h4 class="dog-title"><strong>Animal ID:</strong> <%= dog.animal_id %></h4>
          <h4 class="dog-title"><strong>Name:</strong> <%= dog.name %></h4>
            <ul>
              <li class="description"><strong>Gender:</strong> <%= dog.gender %></li>
              <li class="description"><strong>Weight:</strong> <%= dog.weight %> lbs</li>
              <li class="description"><strong>Age:</strong> <%= dog.age %></li>
              <li class="description"><strong>Breed Type:</strong> <%= dog.breed_type %></li>
              <li class="description"><strong>Primary Breed:</strong> <%= dog.breed_one %></li>
              <li class="description"><strong>Secondary Breed:</strong> <%= dog.breed_two %></li>
              <li class="description"><strong>Cat Compatibility:</strong> <%= dog.cat_compatible %></li>
              <li class="description"><strong>Dog Compatibility:</strong> <%= dog.dog_compatible %></li>
              <li class="description"><strong>Human Compatibility:</strong> <%= dog.human_compatible %></li>
              <li class="description"><strong>Energy Level:</strong> <%= dog.energy_level %></li>
              <li class="description"><strong>Temperament:</strong> <%= dog.temperament %></li>
              <li class="description"><strong>Adoption Fee:</strong> $<%= dog.fee %></li>
            </ul>  
          <p class="dog-description"><%= dog.description %></p>
        </div><!-- /.col-md-4 foster-profile-->  
       <%#= will_paginate @dogs %>
      <% end %>
    </div><!-- /.row space -->
  <% end %>
</div><!-- /.container -->

app/views/dogs/michigan.html.erb
<!-- Adoptable Dog page -->
<!-- Styling supported by dogs.scss -->
<div class="container">

  <!-- Adoptable Dogs Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="headers">Adoptable Dogs</h1>
      <p>Dogs on this page are located in the Michigan area, and are ready for adoption. Please submit an application with the <i>dog's name</i> and <i>animal ID number</i> if you are interested in adoptiong.</p>
    </div>
  </div><!-- /.row -->   

  <!-- 3 columns per row -->
  <% @dogs.each_slice(3) do |dogs| %>
    <div class="row space"> 
      <% dogs.each do |dog| %> 
         <div class="col-md-4 adoptable-profile">
          <p><%= image_tag dog.image_url(:thumb), class: "img-responsive img-adoptable center-block" %><p>
          <h4 class="dog-title"><strong>Animal ID:</strong> <%= dog.animal_id %></h4>
          <h4 class="dog-title"><strong>Name:</strong> <%= dog.name %></h4>
            <ul>
              <li class="description"><strong>Gender:</strong> <%= dog.gender %></li>
              <li class="description"><strong>Weight:</strong> <%= dog.weight %> lbs</li>
              <li class="description"><strong>Age:</strong> <%= dog.age %></li>
              <li class="description"><strong>Breed Type:</strong> <%= dog.breed_type %></li>
              <li class="description"><strong>Primary Breed:</strong> <%= dog.breed_one %></li>
              <li class="description"><strong>Secondary Breed:</strong> <%= dog.breed_two %></li>
              <li class="description"><strong>Cat Compatibility:</strong> <%= dog.cat_compatible %></li>
              <li class="description"><strong>Dog Compatibility:</strong> <%= dog.dog_compatible %></li>
              <li class="description"><strong>Human Compatibility:</strong> <%= dog.human_compatible %></li>
              <li class="description"><strong>Energy Level:</strong> <%= dog.energy_level %></li>
              <li class="description"><strong>Temperament:</strong> <%= dog.temperament %></li>
              <li class="description"><strong>Adoption Fee:</strong> $<%= dog.fee %></li>
            </ul>  
          <p class="dog-description"><%= dog.description %></p>
        </div><!-- /.col-md-4 adoptable-profile-->  
       <%#= will_paginate @dogs %>
      <% end %>
    </div><!-- /.row space -->
  <% end %>
</div><!-- /.container -->

app/views/dogs/new.html.erb
<div class="container-fluid">
  <div class="row">
	<%= render 'dogs/form' %>
  </div>	
</div>

app/views/dogs/show.html.erb
<!-- Display single dog after being entered into form -->
<div class="container-fluid">

  <!-- Individual Dog Page Header -->
  <div class="row space">
    <div class="col-lg-12">
      <h1 class="headers">Individual Dog Info</h1>
      <p class="adoptable-header">This displays the dog you just entered. The <i>Back</i> button will return you to the <i>Enter A New Dog</i> page. Or you can click the <i>Edit</i> button to make changes for any dog already added to either the Foster or Adoptable page.</p>
    </div>
  </div><!-- /.row -->  

  <div class="row">
    <div class="col-md-4">
      <%= link_to 'Back', new_dog_path, class: 'btn btn-primary pull-right' %> 
    </div>
    <div class="col-md-4">
      <div class="adoptable-profile">
        <p><%= image_tag @dog.image_url(:thumb), class: "img-responsive img-adoptable center-block" %><p>
        <h4 class="dog-title"><strong>Animal ID:</strong> <%= @dog.animal_id %> | <strong>Name:</strong> <%= @dog.name %></h4>
        <ul>
          <li class="description"><strong>Gender:</strong> <%= @dog.gender %></li>
          <li class="description"><strong>Weight:</strong> <%= @dog.weight %> lbs</li>
          <li class="description"><strong>Age:</strong> <%= @dog.age %></li>
          <li class="description"><strong>Breed Type:</strong> <%= @dog.breed_type %></li>
          <li class="description"><strong>Primary Breed:</strong> <%= @dog.breed_one %></li>
          <li class="description"><strong>Secondary Breed:</strong> <%= @dog.breed_two %></li>
          <li class="description"><strong>Cat Compatibility:</strong> <%= @dog.cat_compatible %></li>
          <li class="description"><strong>Dog Compatibility:</strong> <%= @dog.dog_compatible %></li>
          <li class="description"><strong>Human Compatibility:</strong> <%= @dog.human_compatible %></li>
          <li class="description"><strong>Energy Level:</strong> <%= @dog.energy_level %></li>
          <li class="description"><strong>Temperament:</strong> <%= @dog.temperament %></li>
          <li class="description"><strong>Adoption Fee:</strong> $<%= @dog.fee %></li>
        </ul>
        <p class="description"><%= @dog.description %></p>    
      </div><!-- adoptable-profile -->
    </div><!-- col-md-3 -->
    <div class="col-md-4">
      <%= link_to 'Edit', edit_dog_path, class: 'btn btn-success pull-left' %> 
    </div>
  </div><!-- row -->  
</div><!-- container -->