config/routes.rb
Rails.application.routes.draw do
  

  #Display for foster dogs
  resources :dogs   
    
  #Display for adoptable dogs
  get 'michigan' => 'dogs#michigan'
  post 'michigan' => 'dogs#michigan'

  get 'donate' => 'dogs#donate'

  #Display adoption info and form partial application
  get 'adoption' => 'dogs#adoption'

  devise_for :users
  
  #For Contact Form pg 
  resources :contacts, only: [:new, :create, :destroy]

  #Remove uploaded attachment on Contact Form pg
  delete 'contacts' => 'contacts#destroy'

  #Display Contact Form acceptance to user
  get 'accept' => 'contacts#accept'

  #Displays Dog's Journey pg
  get 'welcome/show'

  get 'about' => 'welcome#about'

  #Displays About Us pg
  post 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/views/shared/_footer.html.erb
<footer class="container-fluid bg-blue">
  <div class="row">
    <div class="col-md-4">
      <p>Compass Dog Rescue<span class='glyphicon glyphicon-copyright-mark'></span> 2017 
      </p>
    </div>
    <div class="col-md-4 center-logos">
    <!-- Facebook Logo -->
      <p><%= link_to image_tag("FB-f-Logo__white_57.png", class: "img-responsive center-block"), "https://www.facebook.com/compassdogrescue/?fref=ts", alt: "Facebook Logo", target: "_blank" %>
      </p>
    </div>
    <div class="col-md-4">
      <p class="pull-right"><%= link_to "Back To Top", "#", class: "btn btn-default" %>
      </p>
    </div>
  </div><!-- row -->
</footer>

   

app/views/shared/_jumbotron.html.erb
<div class="container">
  <div class="jumbotron">
    <div class="row">
      <div class="col-lg-12">
        <h1 id="compass-title">Compass Dog Rescue</h1> 
  	    <%= image_tag("MapImage.png", class: "img-responsive img-map center-block", alt: "Compass map") %>
  	  </div>
  	</div>
  </div><!-- /.jumbotron --> 
</div><!-- /.container -->

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <a class="navbar-brand"><%= link_to image_tag("CompassPawsOne.png", class: "img-responsive img-logo center-block", alt: "Compass Logo"), root_path %></a> 
    </div><!-- navbar-header -->

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">   
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About Us", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Our Dogs<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Our Dogs Journey", welcome_show_path %><li>
            <li><%= link_to "Foster Dogs", dogs_path %><li>
            <li><%= link_to "Adoptable Dogs", michigan_path %><li>
          </ul>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Foster or Adopt<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Foster Application", welcome_show_path %><li>
              <li><%= link_to "Adoption Application", adoption_path %><li>
            </ul>
          </li>
        </li>
        <li><%= link_to "Ways To Help", donate_path %></li>
        <li><%= link_to "Contact Us", new_contact_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>   
      </ul><!-- nav navbar-nav -->
    </div><!--/.nav-collapse -->
  </div><!-- container -->
</nav>
          
      
       

app/views/shared/_paypal.html.erb
<!-- PayPal Logo -->
<table border="0" cellpadding="10" cellspacing="0" align="center">
  <tr>
    <td align="center">
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;">
      <img src="https://www.paypalobjects.com/webstatic/mktg/logo/pp_cc_mark_37x23.jpg" border="0" alt="PayPal Logo">
      </a>
  </td>
  </tr>
</table><!-- PayPal Logo -->